import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Timer",
    description: "Generated by RjR",
  };

export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body>{children}</body>
      </html>
    );
  }